version: "3.8"
services:
  db:
    image: postgres:14.5-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
  app:
    build: .
    depends_on:
      - db
